### ISSUE TITLE
CheckList

### ISSUE THREAD

**Issue by johnnynunez** [dusty-nv/jetson-containers#632]
ML:
- [x] Tensorflow builds with Hermetic CUDA. 

Robotics:
- [x] Crossformer [https://github.com/octo-models/octo]
- [x] Octo [https://github.com/feizc/Dimba] 

Mamba:
- [x] Dimba [https://github.com/feizc/Dimba] 
- [ ] Cobra 

ComfyUI:
- [x] ComfyUI3D [https://github.com/MrForExample/ComfyUI-3D-Pack]
